// <auto-generated />
namespace CalculadoraNash.Infra.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class inicializando : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(inicializando));
        
        string IMigrationMetadata.Id
        {
            get { return "201805092311042_inicializando"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
